name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  security-events: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      
      - name: Run IaC scan
        uses: accuknox/iac-scan-action@v0.0.1
        with:
          directory: ./  
          output_file_path: ./results
          token: 5088
          endpoint: "cspm.stage.accuknox.com"
          tenant_id: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxODg0OTM3OTY5LCJqdGkiOiI0MDc3YWI5MTdlNTQ0NGEwYTFmNmExZTYzYWM5ZGVjYyIsImlzcyI6ImNzcG0uc3RhZ2UuYWNjdWtub3guY29tIn0.RUAFGIfS8NhZ83SZ-Rkw07-BIdXWpRjAbqTLzJvYz8Z-cjxJ4uUvH-h3-xGMpQ26a_tA8h1AvzM60L2pS338QA0CRVZrH0WTtNNagb2eNJdnYOH6YW7sdDAWE78SroRS8nKZFGyvGAILz7iDyNcf_rXybAhTCN-zjIjv1Hy73dECO0KCgx9j6_hB7Eyhqdm8_RmJZStL9sSyyywNLyUDMMsP35ah42ARdiF2OB3_fQIwrIRS9ICoAtCqRW6sTh4ctzfdv4PPJFsOeuxzl3pEpVPnwj7yR9QZojD5LjiZujK6k8WhVKZRQMPtCJ9HKm_igIDC4qGh0Yqi9qV35MEe8g
          quiet: "true"
          soft_fail: "true"
